[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "edi"
authors = [{name = "Zhongcan Xiao", email = "zhongcanxiao@utexas.edu"}]
dynamic = ["version", "description"]
